name: ncertclass1to12th
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  easy_localization: ^3.0.0
  file_picker: ^4.2.3
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.1.1
  flutter_local_notifications: ^9.1.2
  flutter_rating_bar: ^4.0.0
  flutter_switch: ^0.3.2
  flutter_zoom_drawer: ^2.1.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  in_app_review: ^2.0.2
  liquid_progress_indicator: ^0.4.0
  logger: ^1.1.0
  lottie: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.1
  share_plus: ^3.0.4
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  url_launcher: ^6.0.9
  sliding_up_panel: ^2.0.0+1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.0
  introduction_screen: ^2.1.0
  uc_pdfview: ^0.0.3
  in_app_update: ^2.0.0
  youtube_player_iframe: ^2.2.2
  flutter_inappwebview: ^5.3.2
  flutter_colorpicker: ^1.0.3
  http: ^0.13.4
  cloud_firestore: ^3.1.7
  google_mobile_ads: ^1.0.1
  


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/header/
    - assets/classimg/
    - assets/translations/
    #videos
    - assets/videoscources/
    #exam
    - assets/exam/
    - assets/boardimage/

    #data_image
    - assets/alldata_image/all/
    - assets/alldata_image/class9/data_image/
    - assets/alldata_image/class10/data_image/
    - assets/alldata_image/class11/data_image/
    - assets/alldata_image/class12/data_image/
    - assets/Paper/class10/
    - assets/Paper/class12/
    - assets/board/
    #class 9
    - assets/ncert/class9/
    - assets/ncert/class9/subject/
    - assets/ncert/class9/book/
    - assets/ncert/class9/solution/
    #class 9 exampler
    - assets/exampler/class9/
    - assets/exampler/class9/subject/
    - assets/exampler/class9/book/

    #class 10
    - assets/ncert/class10/
    - assets/ncert/class10/subject/
    - assets/ncert/class10/book/
    - assets/ncert/class10/solution/
    #class 10 exampler
    - assets/exampler/class10/
    - assets/exampler/class10/subject/
    - assets/exampler/class10/book/

    #class 11
    - assets/ncert/class11/
    - assets/ncert/class11/subject/
    - assets/ncert/class11/book/accountacy/
    - assets/ncert/class11/book/biology/
    - assets/ncert/class11/book/chemistry/
    - assets/ncert/class11/book/english/
    - assets/ncert/class11/book/geography/
    - assets/ncert/class11/book/hindi/
    - assets/ncert/class11/book/history/
    - assets/ncert/class11/book/math/
    - assets/ncert/class11/book/physics/
    - assets/ncert/class11/book/politicalscience/
    - assets/ncert/class11/book/psychology/
    - assets/ncert/class11/book/sociology/
    - assets/ncert/class11/book/economics/


    - assets/ncert/class11/solution/accountacy/
    - assets/ncert/class11/solution/biology/
    - assets/ncert/class11/solution/chemistry/
    - assets/ncert/class11/solution/english/
    - assets/ncert/class11/solution/geography/
    - assets/ncert/class11/solution/hindi/
    - assets/ncert/class11/solution/history/
    - assets/ncert/class11/solution/math/
    - assets/ncert/class11/solution/physics/
    - assets/ncert/class11/solution/politicalscience/
    - assets/ncert/class11/solution/psychology/
    - assets/ncert/class11/solution/sociology/
    - assets/ncert/class11/solution/economics/


    #class 11 exampler
    - assets/exampler/class11/
    - assets/exampler/class11/subject/
    - assets/exampler/class11/book/biology/
    - assets/exampler/class11/book/math/
    - assets/exampler/class11/book/chemistry/
    - assets/exampler/class11/book/physics/


    #class 12
    - assets/ncert/class12/
    - assets/ncert/class12/subject/
    - assets/ncert/class12/book/accountacy/
    - assets/ncert/class12/book/biology/
    - assets/ncert/class12/book/chemistry/
    - assets/ncert/class12/book/english/
    - assets/ncert/class12/book/geography/
    - assets/ncert/class12/book/hindi/
    - assets/ncert/class12/book/history/
    - assets/ncert/class12/book/math/
    - assets/ncert/class12/book/physics/
    - assets/ncert/class12/book/politicalscience/
    - assets/ncert/class12/book/psychology/
    - assets/ncert/class12/book/sociology/


    - assets/ncert/class12/solution/accountacy/
    - assets/ncert/class12/solution/biology/
    - assets/ncert/class12/solution/chemistry/
    - assets/ncert/class12/solution/english/
    - assets/ncert/class12/solution/geography/
    - assets/ncert/class12/solution/hindi/
    - assets/ncert/class12/solution/history/
    - assets/ncert/class12/solution/math/
    - assets/ncert/class12/solution/physics/
    - assets/ncert/class12/solution/politicalscience/
    - assets/ncert/class12/solution/psychology/
    - assets/ncert/class12/solution/sociology/



    #class 12 exampler
    - assets/exampler/class12/
    - assets/exampler/class12/subject/
    - assets/exampler/class12/book/biology/
    - assets/exampler/class12/book/math/
    - assets/exampler/class12/book/chemistry/
    - assets/exampler/class12/book/physics/



 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
